// config.bin - 22:04:24 01/06/20, generated in 0.12 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class KP_Ranks {
		author = "Wyqer";
		name = "KP Ranks";
		url = "https://github.com/KillahPotatoes/KP-Ranks";
		units[] = {"KPR_force"};
		weapons[] = {};
		requiredVersion = 1.84;
		requiredAddons[] = {"A3_Modules_F", "cba_main"};
		versionDesc = "KP Ranks";
		version = 2.0.2;
		versionStr = 2.0.2;
		versionAr[] = {2, 0, 2};
		authors[] = {"Wyqer,TopDen"};
	};
};

class CfgSettings {
	class CBA {
		class Versioning {
			class KP_Ranks {
				main_addon = "\KP_Ranks";
				
				class Dependencies {
					CBA[] = {"cba_main", {3, 7, 1}, "true"};
				};
			};
		};
	};
};

class Extended_PreInit_EventHandlers {
	class KPR_preInit {
		init = "[] call KPR_fnc_initCBA";
	};
};

class Extended_PostInit_EventHandlers {
	class KPR_postInit {
		init = "[] call KPR_fnc_initRanks";
	};
};

class CfgFactionClasses {
	class NO_CATEGORY;	// External class reference
	
	class KPR_Category : NO_CATEGORY {
		displayName = "KP Ranks";
	};
};

class CfgVehicles {
	class Logic;	// External class reference
	
	class Module_F : Logic {
		class AttributesBase {
			class Default;	// External class reference
			class ModuleDescription;	// External class reference
		};
		
		class ModuleDescription {
			class AnyBrain;	// External class reference
		};
	};
	
	class KPR_force : Module_F {
		scope = 2;
		displayName = "Force KP Ranks";
		icon = "\KP_Ranks\kplogo_ca.paa";
		category = "KPR_Category";
		function = "KPR_fnc_forceRanks";
		functionPriority = 1;
		isGlobal = 0;
		isTriggerActivated = 0;
		isDisposable = 0;
		is3DEN = 0;
		
		class Attributes : AttributesBase {
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description[] = {$STR_KPR_CONFIG_MODULEDESC1, $STR_KPR_CONFIG_MODULEDESC2};
			position = 0;
			direction = 0;
			optional = 1;
			duplicate = 0;
		};
	};
};

class CfgFunctions {
	class KPR {
		class KP_Ranks {
			file = "\KP_Ranks\fnc";
			
			class addActions {};
			
			class addPlayer {};
			
			class addScore {};
			
			class applyRank {};
			
			class autoLoop {};
			
			class entityKilled {};
			
			class forceRanks {};
			
			class getAceKiller {};
			
			class getInsigniaData {};
			
			class getPlayerIndex {};
			
			class getPlaytime {};
			
			class getPlaytimePlain {};
			
			class getRank {};
			
			class getRankName {};
			
			class getRankScore {};
			
			class getRankScoreNext {};
			
			class getScore {};
			
			class getUniformIndex {};
			
			class hasRank {};
			
			class initACE {};
			
			class initCBA {};
			
			class initRanks {};
			
			class isAdmin {};
			
			class levelAnnounce {};
			
			class openDialogPlayers {};
			
			class openDialogUniforms {};
			
			class playerAddEdit {};
			
			class playerDeath {};
			
			class playerExport {};
			
			class playerImport {};
			
			class playerSave {};
			
			class playerSaveServer {};
			
			class savePlayers {};
			
			class saveUniforms {};
			
			class scoreUpdate {};
			
			class sendAceKiller {};
			
			class setDefaultUniforms {};
			
			class setRank {};
			
			class setScore {};
			
			class showHint {};
			
			class uniformExport {};
			
			class uniformFill {};
			
			class uniformImport {};
			
			class uniformLBChange {};
			
			class uniformMove {};
			
			class uniformSave {};
			
			class updatePlayer {};
		};
	};
};

class CfgUnitInsignia {
	class KPR_BWF_0 {
		author = "Nils";
		displayName = "BWF00 Schuetze";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd0_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_1 {
		author = "Nils";
		displayName = "BWF01 Gefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_2 {
		author = "Nils";
		displayName = "BWF02 Obergefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd2_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_3 {
		author = "Nils";
		displayName = "BWF03 Hauptgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_4 {
		author = "Nils";
		displayName = "BWF04 Stabsgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd4_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_5 {
		author = "Nils";
		displayName = "BWF05 Oberstabsgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd5_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_6 {
		author = "Nils";
		displayName = "BWF06 Unteroffizier";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_7 {
		author = "Nils";
		displayName = "BWF07 Stabsunteroffizier";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd7_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_8 {
		author = "Nils";
		displayName = "BWF08 Feldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_9 {
		author = "Nils";
		displayName = "BWF09 Oberfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd9_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_10 {
		author = "Nils";
		displayName = "BWF10 Hauptfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd10_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_11 {
		author = "Nils";
		displayName = "BWF11 Stabsfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_12 {
		author = "Nils";
		displayName = "BWF12 Oberstabsfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd12_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_13 {
		author = "Nils";
		displayName = "BWF13 Leutenant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd13_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_14 {
		author = "Nils";
		displayName = "BWF14 Oberleutnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd14_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_15 {
		author = "Nils";
		displayName = "BWF15 Hauptmann";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_16 {
		author = "Nils";
		displayName = "BWF16 Stabshauptmann";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd16_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_17 {
		author = "Nils";
		displayName = "BWF17 Major";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd17_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_18 {
		author = "Nils";
		displayName = "BWF18 Oberstleutnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd18_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWF_19 {
		author = "Nils";
		displayName = "BWF19 Oberst";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\green\kpd19_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_0 {
		author = "Nils";
		displayName = "BWT00 Schuetze";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd0_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_1 {
		author = "Nils";
		displayName = "BWT01 Gefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_2 {
		author = "Nils";
		displayName = "BWT02 Obergefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd2_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_3 {
		author = "Nils";
		displayName = "BWT03 Hauptgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_4 {
		author = "Nils";
		displayName = "BWT04 Stabsgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd4_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_5 {
		author = "Nils";
		displayName = "BWT05 Oberstabsgefreiter";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd5_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_6 {
		author = "Nils";
		displayName = "BWT06 Unteroffizier";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_7 {
		author = "Nils";
		displayName = "BWT07 Stabsunteroffizier";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd7_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_8 {
		author = "Nils";
		displayName = "BWT08 Feldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_9 {
		author = "Nils";
		displayName = "BWT09 Oberfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd9_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_10 {
		author = "Nils";
		displayName = "BWT10 Hauptfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd10_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_11 {
		author = "Nils";
		displayName = "BWT11 Stabsfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_12 {
		author = "Nils";
		displayName = "BWT12 Oberstabsfeldwebel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd12_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_13 {
		author = "Nils";
		displayName = "BWT13 Leutenant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd13_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_14 {
		author = "Nils";
		displayName = "BWT14 Oberleutnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd14_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_15 {
		author = "Nils";
		displayName = "BWT15 Hauptmann";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_16 {
		author = "Nils";
		displayName = "BWT16 Stabshauptmann";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd16_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_17 {
		author = "Nils";
		displayName = "BWT17 Major";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd17_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_18 {
		author = "Nils";
		displayName = "BWT18 Oberstleutnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd18_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_BWT_19 {
		author = "Nils";
		displayName = "BWT19 Oberst";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\brown\kpd19_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_0 {
		author = "Degman";
		displayName = "CRO00 Nothing";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "#(rgb,8,8,3)color(0,0,0,0)";
		textureVehicle = "";
	};
	
	class KPR_CRO_1 {
		author = "Degman";
		displayName = "CRO01 Pozornik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_2 {
		author = "Degman";
		displayName = "CRO02 Pozornik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_3 {
		author = "Degman";
		displayName = "CRO03 Razvodnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_4 {
		author = "Degman";
		displayName = "CRO04 Razvodnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_5 {
		author = "Degman";
		displayName = "CRO05 Razvodnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_6 {
		author = "Degman";
		displayName = "CRO06 Skupnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_7 {
		author = "Degman";
		displayName = "CRO07 Desetnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd7_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_8 {
		author = "Degman";
		displayName = "CRO08 Narednik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_9 {
		author = "Degman";
		displayName = "CRO09 Nadnarednik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd9_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_10 {
		author = "Degman";
		displayName = "CRO10 Stozerni Narednik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd10_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_11 {
		author = "Degman";
		displayName = "CRO11 Casnicki Namjesnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_12 {
		author = "Degman";
		displayName = "CRO12 Casnicki Namjesnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_13 {
		author = "Degman";
		displayName = "CRO13 Porucnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd13_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_14 {
		author = "Degman";
		displayName = "CRO14 Natporucnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd14_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_15 {
		author = "Degman";
		displayName = "CRO15 Satnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_16 {
		author = "Degman";
		displayName = "CRO16 Satnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_17 {
		author = "Degman";
		displayName = "CRO17 Bojnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd17_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_18 {
		author = "Degman";
		displayName = "CRO18 Pukovnik";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd18_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_CRO_19 {
		author = "Degman";
		displayName = "CRO19 Brigadir";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\cro\kpd19_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_0 {
		author = "Nils";
		displayName = "USA00 Private E1";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "#(rgb,8,8,3)color(0,0,0,0)";
		textureVehicle = "";
	};
	
	class KPR_USA_1 {
		author = "Nils";
		displayName = "USA01 Private E2";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_2 {
		author = "Nils";
		displayName = "USA02 Private First Class";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd2_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_3 {
		author = "Nils";
		displayName = "USA03 Private First Class";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd2_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_4 {
		author = "Nils";
		displayName = "USA04 Corporal";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd4_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_5 {
		author = "Nils";
		displayName = "USA05 Corporal";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd4_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_6 {
		author = "Nils";
		displayName = "USA06 Sergeant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_7 {
		author = "Nils";
		displayName = "USA07 Sergeant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_8 {
		author = "Nils";
		displayName = "USA08 Staff Sergeant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_9 {
		author = "Nils";
		displayName = "USA09 Staff Sergeant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_10 {
		author = "Nils";
		displayName = "USA10 Sergeant First Class";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd10_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_11 {
		author = "Nils";
		displayName = "USA11 Master Sergeant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_12 {
		author = "Nils";
		displayName = "USA12 Sergeant Major";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd12_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_13 {
		author = "Nils";
		displayName = "USA13 Second Lieutenant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd13_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_14 {
		author = "Nils";
		displayName = "USA14 First Lieutenant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd14_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_15 {
		author = "Nils";
		displayName = "USA15 Captain";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_16 {
		author = "Nils";
		displayName = "USA16 Captain";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_17 {
		author = "Nils";
		displayName = "USA17 Major";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd17_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_18 {
		author = "Nils";
		displayName = "USA18 Lieutenant Colonel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd18_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_USA_19 {
		author = "Nils";
		displayName = "USA19 Colonel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\us\kpd19_ca.paa";
		textureVehicle = "";
	};
	
	
	class KPR_RUS_0 {
		author = "TopDen";
		displayName = "RUS00 Рядовой";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd0_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_1 {
		author = "TopDen";
		displayName = "RUS01 Ефрейтор";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd1_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_2 {
		author = "TopDen";
		displayName = "RUS02 Мл.Сержант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd2_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_3 {
		author = "TopDen";
		displayName = "RUS03 Сержант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd3_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_4 {
		author = "TopDen";
		displayName = "RUS04 Ст.Сержант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd4_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_5 {
		author = "TopDen";
		displayName = "RUS05 Старшина";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd5_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_6 {
		author = "TopDen";
		displayName = "RUS06 Прапорщик";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd6_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_7 {
		author = "TopDen";
		displayName = "RUS07 Ст.Прапорщик";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd7_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_8 {
		author = "TopDen";
		displayName = "RUS08 Мл.Лейтенант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd8_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_9 {
		author = "TopDen";
		displayName = "RUS09 Лейтенант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd9_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_10 {
		author = "TopDen";
		displayName = "RUS10 Ст.Лейтенант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd10_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_11 {
		author = "TopDen";
		displayName = "RUS11 Капитан";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd11_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_12 {
		author = "TopDen";
		displayName = "RUS12 Майор";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd12_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_13 {
		author = "TopDen";
		displayName = "RUS13 Подполковник";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd13_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_14 {
		author = "TopDen";
		displayName = "RUS14 Полковник";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd14_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_15 {
		author = "TopDen";
		displayName = "RUS15 Генерал-майор";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd15_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_16 {
		author = "TopDen";
		displayName = "RUS16 Генерал-лейтенант";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd16_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_17 {
		author = "TopDen";
		displayName = "RUS17 Генерал-полковник";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd17_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_18 {
		author = "TopDen";
		displayName = "RUS18 Генерал армии";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd18_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_RUS_19 {
		author = "TopDen";
		displayName = "RUS19 Маршал РФ";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\rus\kpd19_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_DK_0 {
		author = "Platoon of Danes";
		displayName = "DK00 Rekrut";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd0_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_DK_1 {
		author = "Platoon of Danes";
		displayName = "DK01 Konstabel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd1_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_2 {
		author = "Platoon of Danes";
		displayName = "DK02 Overkonstabel";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd2_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_3 {
		author = "Platoon of Danes";
		displayName = "DK03 Overkonstabel af 1.Grad";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd3_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_4 {
		author = "Platoon of Danes";
		displayName = "DK04 Korporal";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd4_ca.paa";
		textureVehicle = "";
	};


	class KPR_DK_5 {
		author = "Platoon of Danes";
		displayName = "DK05 Sergentelev";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd5_ca.paa";
		textureVehicle = "";
	};
	
	class KPR_DK_6 {
		author = "Platoon of Danes";
		displayName = "DK06 Sergent";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd6_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_7 {
		author = "Platoon of Danes";
		displayName = "DK07 Oversergent";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd7_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_8 {
		author = "Platoon of Danes";
		displayName = "DK08 Seniorsergent";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd8_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_9 {
		author = "Platoon of Danes";
		displayName = "DK09 Løjtnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd9_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_10 {
		author = "Platoon of Danes";
		displayName = "DK10 Premierløjtnant";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd10_ca.paa";
		textureVehicle = "";
	};

	class KPR_DK_11 {
		author = "Platoon of Danes";
		displayName = "DK11 Kaptajn";
		material = "\A3\Ui_f\data\GUI\Cfg\UnitInsignia\default_insignia.rvmat";
		texture = "\KP_Ranks\ranks\dk\kpd11_ca.paa";
		textureVehicle = "";
	};
};
class ScrollBar;	// External class reference
class RscActivePicture;	// External class reference
class RscActiveText;	// External class reference
class RscButton;	// External class reference
class RscCheckBox;	// External class reference
class RscCombo;	// External class reference
class RscControlsGroup;	// External class reference
class RscEdit;	// External class reference
class RscListBox;	// External class reference
class RscListNBox;	// External class reference
class RscShortcutButton;	// External class reference
class RscText;	// External class reference
class RscXListBox;	// External class reference
class RscXSliderH;	// External class reference

class KP_Title : RscText {
	colorBackground[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.13])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.54])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.21])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"};
	text = "DIALOG TITLE";
	h = "safeZoneH * 0.035";
	shadow = 1;
	sizeEx = "safeZoneH * 0.03";
};

class KP_CloseCross : RscActiveText {
	style = 48;
	color[] = {1, 1, 1, 0.75};
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 0.75};
	colorActive[] = {1, 1, 1, 1};
	text = "\A3\Ui_f\data\GUI\Rsc\RscDisplayArcadeMap\icon_exit_cross_ca.paa";
	w = "safeZoneW * 0.014";
	h = "safeZoneH * 0.025";
	tooltip = $STR_DISP_CLOSE;
	action = "closeDialog 0";
};

class KP_Background : RscText {
	colorBackground[] = {0, 0, 0, 0.5};
};

class KP_Text : RscText {
	sizeEx = "safeZoneH * 0.02";
};

class KP_InlineTitle : RscText {
	style = 2;
	sizeEx = "safeZoneH * 0.025";
};

class KP_ActiveText : RscActiveText {
	style = 2;
	sizeEx = "safeZoneH * 0.02";
};

class KP_Picture : RscText {
	style = 48;
};

class KP_ActivePicture : RscActivePicture {};

class KP_PictureRatio : RscText {
	style = 48 + 2048;
};

class KP_Button : RscButton {
	colorBackground[] = {0, 0, 0, 0.5};
	colorFocused[] = {0, 0, 0, 0.5};
	h = "safeZoneH * 0.025";
	sizeEx = "safeZoneH * 0.02";
};

class KP_InlineButton : RscButton {
	colorBackground[] = {0.25, 0.25, 0.25, 1};
	colorBackgroundDisabled[] = {0, 1, 0, 1};
	colorBackgroundActive[] = {0.3, 0.3, 0.3, 1};
	colorFocused[] = {0.25, 0.25, 0.25, 1};
	sizeEx = "safeZoneH * 0.02";
	offsetPressedX = "safeZoneW * 0.0005";
	offsetPressedY = "safeZoneH * 0.001";
};

class KP_ControlsGroup : RscControlsGroup {};

class KP_Combo : RscCombo {
	colorBackground[] = {0, 0, 0, 0.5};
	sizeEx = "safeZoneH * 0.02";
};

class KP_CheckBox : RscCheckBox {
	style = 2;
	w = "safeZoneW * 0.014";
	h = "safeZoneH * 0.025";
};

class KP_ListBox : RscListBox {
	sizeEx = "safeZoneH * 0.02";
};

class KP_ListNBox : RscListNBox {
	sizeEx = "safeZoneH * 0.02";
};

class KP_XListBox : RscXListBox {
	colorBackground[] = {0, 0, 0, 0.5};
	sizeEx = "safeZoneH * 0.02";
};

class KP_Slider : RscXSliderH {
	color[] = {1, 1, 1, 0.6};
	colorActive[] = {1, 1, 1, 0.6};
};

class KP_EditBox : RscEdit {
	colorBackground[] = {0, 0, 0, 0.3};
	sizeEx = "safeZoneH * 0.02";
};

class KP_DialogTitle : KP_Title {
	x = "safeZoneX + safeZoneW * (0.25 + 0 * ((1 - 2 * 0.25) + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * 0.2";
	w = "safeZoneW * (((1 - 2 * 0.25) - (1 - 1) * 0.002) / 1)";
};

class KP_DialogCross : KP_CloseCross {
	x = "safeZoneX + safeZoneW * (1 - 0.25 - 0.02)";
	y = "safeZoneY + safeZoneH * (0.2 + 0.005)";
};

class KP_DialogBackground : KP_Background {
	x = "safeZoneX + safeZoneW * (0.25 + 0 * ((1 - 2 * 0.25) + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * (0.2 + 0.035 + 0.004)";
	w = "safeZoneW * (((1 - 2 * 0.25) - (1 - 1) * 0.002) / 1)";
	h = "safeZoneH * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004)";
};

class KP_DialogButton : KP_Button {
	x = "safeZoneX + safeZoneW * (0.25 + 0 * ((1 - 2 * 0.25) + 0.002) / 4)";
	y = "safeZoneY + safeZoneH * (0.2 + 0.035 + 2 * 0.004 + (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004))";
	w = "safeZoneW * (((1 - 2 * 0.25) - (4 - 1) * 0.002) / 4)";
};

class KP_DialogTitleL : KP_Title {
	x = "safeZoneX + safeZoneW * (0.15 + 0 * ((1 - 2 * 0.15) + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * 0.15";
	w = "safeZoneW * (((1 - 2 * 0.15) - (1 - 1) * 0.002) / 1)";
};

class KP_DialogCrossL : KP_CloseCross {
	x = "safeZoneX + safeZoneW * (1 - 0.15 - 0.02)";
	y = "safeZoneY + safeZoneH * (0.15 + 0.005)";
};

class KP_DialogBackgroundL : KP_Background {
	x = "safeZoneX + safeZoneW * (0.15 + 0 * ((1 - 2 * 0.15) + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * (0.15 + 0.035 + 0.004)";
	w = "safeZoneW * (((1 - 2 * 0.15) - (1 - 1) * 0.002) / 1)";
	h = "safeZoneH * (1 - 2 * 0.15 - 0.035 - 0.025 - 2 * 0.004)";
};

class KP_DialogButtonL : KP_Button {
	x = "safeZoneX + safeZoneW * (0.15 + 0 * ((1 - 2 * 0.15) + 0.002) / 4)";
	y = "safeZoneY + safeZoneH * (0.15 + 0.035 + 2 * 0.004 + (1 - 2 * 0.15 - 0.035 - 0.025 - 2 * 0.004))";
	w = "safeZoneW * (((1 - 2 * 0.15) - (4 - 1) * 0.002) / 4)";
};

class KP_DialogTitleC : KP_Title {
	x = "safeZoneX + safeZoneW * (0.035 + 0 * (0.2 + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * 0.05";
	w = "safeZoneW * ((0.2 - (1 - 1) * 0.002) / 1)";
};

class KP_DialogCrossC : KP_CloseCross {
	x = "safeZoneX + safeZoneW * (0.035 + 0.2 - 0.02)";
	y = "safeZoneY + safeZoneH * (0.05 + 0.005)";
};

class KP_DialogBackgroundC : KP_Background {
	x = "safeZoneX + safeZoneW * (0.035 + 0 * (0.2 + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * (0.05 + 0.035 + 0.004)";
	w = "safeZoneW * ((0.2 - (1 - 1) * 0.002) / 1)";
	h = "safeZoneH * (0.75 - 0.035 - 0.025 - 2 * 0.004)";
};

class KP_DialogButtonC : KP_Button {
	x = "safeZoneX + safeZoneW * (0.035 + 0 * (0.2 + 0.002) / 1)";
	y = "safeZoneY + safeZoneH * (0.05 + 0.035 + 2 * 0.004 + (0.75 - 0.035 - 0.025 - 2 * 0.004))";
	w = "safeZoneW * ((0.2 - (1 - 1) * 0.002) / 1)";
};

class KPR_playerList {
	idd = 7580821;
	movingEnable = 0;
	onLoad = "KPR_editPlayers = [[],[]]";
	onUnload = "KPR_editPlayers = nil";
	
	class controlsBackground {
		class KPR_DialogTitle : KP_DialogTitle {
			text = $STR_KPR_DIALOG_PLAYERMANAGE;
		};
		
		class KPR_DialogBackground : KP_DialogBackground {};
	};
	
	class controls {
		class KPR_ControlsGroup : KP_ControlsGroup {
			idc = 75801;
			x = "safeZoneX + safeZoneW * (0.25 + (0 * (1 - 2 * 0.25) + (1 - 0) * 0.002) / 1)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (0 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (1 - 0) * 0.004) / 1)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (1 + 1) * 0.002) / 1)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (1 + 1) * 0.004) / 1)";
			
			class controls {
				class KPR_HeaderBackground : KP_Text {
					colorBackground[] = {0, 0, 0, 0.5};
					x = 0;
					y = 0;
					w = "safeZoneW * (((1 - 2 * 0.25) - (1 + 1) * 0.002) / 1)";
					h = "safeZoneH * 0.04";
				};
				
				class KPR_HeaderName : KP_Text {
					style = 2;
					text = $STR_KPR_DIALOG_PLAYER;
					x = "safeZoneW * 0.01";
					y = "safeZoneH * 0.005";
					w = "safeZoneW * 0.08";
					h = "safeZoneH * 0.03";
					sizeEx = "safeZoneH * 0.025";
				};
				
				class KPR_HeaderAdmin : KPR_HeaderName {
					text = $STR_KPR_DIALOG_ADMIN;
					x = "safeZoneW * 0.11";
				};
				
				class KPR_HeaderRank : KPR_HeaderName {
					text = $STR_KPR_DIALOG_RANK;
					x = "safeZoneW * 0.21";
				};
				
				class KPR_HeaderNation : KPR_HeaderName {
					text = $STR_KPR_DIALOG_NATION;
					x = "safeZoneW * 0.31";
				};
				
				class KPR_HeaderDelete : KPR_HeaderName {
					text = $STR_KPR_DIALOG_DEL;
					x = "safeZoneW * 0.41";
				};
			};
		};
		
		class KPR_DialogButtonS1 : KP_DialogButton {
			text = $STR_KPR_DIALOG_RESET;
			tooltip = $STR_KPR_DIALOG_RESETDESC;
			onButtonClick = "closeDialog 0; [{!dialog}, {call KPR_fnc_openDialogPlayers;}] call CBA_fnc_waitUntilAndExecute";
		};
		
		class KPR_DialogButtonS2 : KP_DialogButton {
			idc = 75802;
			x = "safeZoneX + safeZoneW * (0.25 + 1 * ((1 - 2 * 0.25) + 0.002) / 4)";
			text = $STR_KPR_DIALOG_IMPORT;
			tooltip = $STR_KPR_DIALOG_IMPORTDESC;
			onButtonClick = "call KPR_fnc_playerImport";
		};
		
		class KPR_DialogButtonS3 : KP_DialogButton {
			x = "safeZoneX + safeZoneW * (0.25 + 2 * ((1 - 2 * 0.25) + 0.002) / 4)";
			text = $STR_KPR_DIALOG_EXPORT;
			tooltip = $STR_KPR_DIALOG_EXPORTDESC;
			onButtonClick = "call KPR_fnc_playerExport";
		};
		
		class KPR_DialogButtonS4 : KP_DialogButton {
			x = "safeZoneX + safeZoneW * (0.25 + 3 * ((1 - 2 * 0.25) + 0.002) / 4)";
			text = $STR_KPR_DIALOG_SAVE;
			tooltip = $STR_KPR_DIALOG_SAVEDESC;
			onButtonClick = "call KPR_fnc_playerSave";
		};
		
		class KPR_DialogCross : KP_DialogCross {};
	};
};

class KPR_uniformList {
	idd = 7580822;
	movingEnable = 0;
	onLoad = "KPR_activeUniforms = []; KPR_inactiveUniforms = []";
	onUnload = "KPR_activeUniforms = nil; KPR_inactiveUniforms = nil;";
	
	class controlsBackground {
		class KPR_DialogTitle : KP_DialogTitle {
			text = $STR_KPR_DIALOG_UNIFORMMANAGE;
		};
		
		class KPR_DialogBackground : KP_DialogBackground {};
		
		class KP_HeaderActive : KP_Text {
			style = 2;
			colorBackground[] = {0, 0, 0, 0.5};
			x = "safeZoneX + safeZoneW * (0.25 + (0 * (1 - 2 * 0.25) + (1 - 0) * 0.002) / 1)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (0 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 0) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (8 + 1) * 0.004) / 8)";
			text = $STR_KPR_DIALOG_UNIFORMACTIVE;
			sizeEx = "safeZoneH * 0.025";
		};
		
		class KP_HeaderDetails : KP_Text {
			style = 2;
			colorBackground[] = {0, 0, 0, 0.5};
			x = "safeZoneX + safeZoneW * (0.25 + (1 * (1 - 2 * 0.25) + (4 - 1) * 0.002) / 4)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (0 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 0) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (2 + 1) * 0.002) / 2)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (8 + 1) * 0.004) / 8)";
			text = $STR_KPR_DIALOG_UNIFORMDETAILS;
			sizeEx = "safeZoneH * 0.025";
		};
		
		class KPR_UniformPicture : KP_PictureRatio {
			idc = 75803;
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (8 - 3) * 0.002) / 8)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (1 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 1) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (2 + 1) * 0.004) / 2)";
			text = "";
		};
		
		class KPR_UniformClass : KP_Text {
			idc = 75804;
			style = 2;
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (8 - 3) * 0.002) / 8)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (5 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 5) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (16 + 1) * 0.004) / 16)";
			text = "";
		};
		
		class KPR_UniformAuthor : KP_Text {
			idc = 75805;
			style = 2;
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (8 - 3) * 0.002) / 8)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (11 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (16 - 11) * 0.004) / 16)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (16 + 1) * 0.004) / 16)";
			text = "";
		};
		
		class KP_HeaderInactive : KP_Text {
			style = 2;
			colorBackground[] = {0, 0, 0, 0.5};
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (4 - 3) * 0.002) / 4)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (0 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 0) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (8 + 1) * 0.004) / 8)";
			text = $STR_KPR_DIALOG_UNIFORMINACTIVE;
			sizeEx = "safeZoneH * 0.025";
		};
	};
	
	class controls {
		class KPR_ListActive : KP_ListBox {
			idc = 75801;
			x = "safeZoneX + safeZoneW * (0.25 + (0 * (1 - 2 * 0.25) + (1 - 0) * 0.002) / 1)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (1 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 1) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (1.15 + 1) * 0.004) / 1.15)";
			onLBSelChanged = "if ((_this select 1) > -1) then {['active', _this select 1] call KPR_fnc_uniformLBChange;}";
		};
		
		class KPR_ListInactive : KP_ListBox {
			idc = 75802;
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (4 - 3) * 0.002) / 4)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (1 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 1) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (1.15 + 1) * 0.004) / 1.15)";
			onLBSelChanged = "if ((_this select 1) > -1) then {['inactive', _this select 1] call KPR_fnc_uniformLBChange;}";
		};
		
		class KPR_ComboFaction : KP_Combo {
			idc = 75806;
			x = "safeZoneX + safeZoneW * (0.25 + (3 * (1 - 2 * 0.25) + (8 - 3) * 0.002) / 8)";
			y = "safeZoneY + safeZoneH * ((0.2 + 0.035 + 0.004) + (6 * (1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) + (8 - 6) * 0.004) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (4 + 1) * 0.002) / 4)";
			h = "safeZoneH * (((1 - 2 * 0.2 - 0.035 - 0.025 - 2 * 0.004) - (16 + 1) * 0.004) / 16)";
		};
		
		class KPR_addActive : KP_DialogButton {
			idc = 75807;
			x = "safeZoneX + safeZoneW * (0.25 + 3 * ((1 - 2 * 0.25) + 0.002) / 8)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (16 - 1) * 0.002) / 16)";
			text = "<<";
			tooltip = $STR_KPR_DIALOG_ADDUNIFORMDESC;
			onButtonClick = "['add'] call KPR_fnc_uniformMove";
		};
		
		class KPR_saveUniform : KPR_addActive {
			idc = 75808;
			x = "safeZoneX + safeZoneW * (0.25 + (7 * (1 - 2 * 0.25) + (16 - 7) * 0.002) / 16)";
			w = "safeZoneW * (((1 - 2 * 0.25) - (8 - 1) * 0.002) / 8)";
			text = $STR_KPR_DIALOG_SAVE;
			onButtonClick = "call KPR_fnc_uniformSave";
		};
		
		class KPR_delActive : KPR_addActive {
			idc = 75809;
			x = "safeZoneX + safeZoneW * (0.25 + 9 * ((1 - 2 * 0.25) + 0.002) / 16)";
			text = ">>";
			tooltip = $STR_KPR_DIALOG_DELUNIFORMDESC;
			onButtonClick = "['del'] call KPR_fnc_uniformMove";
		};
		
		class KPR_DialogButtonS2 : KP_DialogButton {
			idc = 758010;
			text = $STR_KPR_DIALOG_IMPORT;
			tooltip = $STR_KPR_DIALOG_IMPORTDESC;
			onButtonClick = "call KPR_fnc_uniformImport";
		};
		
		class KPR_DialogButtonS3 : KP_DialogButton {
			x = "safeZoneX + safeZoneW * (0.25 + 3 * ((1 - 2 * 0.25) + 0.002) / 4)";
			text = $STR_KPR_DIALOG_EXPORT;
			tooltip = $STR_KPR_DIALOG_EXPORTDESC;
			onButtonClick = "call KPR_fnc_uniformExport";
		};
		
		class KPR_DialogCross : KP_DialogCross {};
	};
};

class cfgMods {
	author = "Wyqer,TopDen";
	timepacked = 1535185053;
};
